controller_list:
  - name: fake_manipulator_controller
    type: $(arg execution_type)
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      []
initial:  # Define initial robot poses.
  - group: manipulator
    pose: home